spring:
  profiles:
    include:
      - aws
cloud:
  aws:
    sqs:
      queue:
        url: https://sqs.ap-northeast-2.amazonaws.com/2637652xxxxx/z-standard-queue
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
    stack:
      auto: false
